version: '3.8'

services:

  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${JDBC_PASS-test}
      - POSTGRES_USER=${JDBC_USER-test}
      - POSTGRES_DB=${JDBC_DATABASE-menucoo}