addSbtPlugin("com.dwijnand"      % "sbt-dynver"    % "4.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.7.0")
addSbtPlugin("io.spray"          % "sbt-revolver"  % "0.9.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"  % "0.9.34")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "2.0.2")
